### PR TITLE
Add MSI Support for Azure plugin. 

### PR DESCRIPTION
**Pull request by yanggangtony**
We had discuss in velero repo , for add msi support.
[https://github.com/vmware-tanzu/velero/pull/6938](https://github.com/vmware-tanzu/velero/pull/6938).

Can azure plugin use this pr to validation the functions.

@anshulahuja98 
Please help to test it in azure cluster.

### CODE REVIEW

**Comment by mykolaichuk** [comment]
Awaiting for MSI support so much. As far as I understood there is no other way to do a backup in AKS cluster with Azure AD authentication with Azure RBAC, right? I followed [this steps](https://github.com/vmware-tanzu/velero-plugin-for-microsoft-azure#option-2-use-azure-ad-workload-identity) and oidcIssuerProfile.issuerUrl was null.

**Comment by yanggangtony** [comment]
@mykolaichuk Hi , this pr is just for test validation.

future , will update it and go to the release version of velero , when the upstream merged .

**Comment by anshulahuja98** [comment]
> Awaiting for MSI support so much. As far as I understood there is no other way to do a backup in AKS cluster with Azure AD authentication with Azure RBAC, right? I followed [this steps](https://github.com/vmware-tanzu/velero-plugin-for-microsoft-azure#option-2-use-azure-ad-workload-identity) and oidcIssuerProfile.issuerUrl was null.

Hi @mykolaichuk I'll need to go through workload Identity setup before I comment further on it's setup

This PR Is particularly for using MSI without workload identity. This support was already there in velero / azure plugin since very long but got inadvertently removed due to some recent refactoring.

**Comment by anshulahuja98** [comment]
Ref Issue: https://github.com/vmware-tanzu/velero/issues/6931

**Comment by yanggangtony** [comment]
@anshulahuja98 
Thanks for confirm .
Rebased the latest upstream velero repo.

**Comment by anshulahuja98** [comment]
@yanggangtony pl also rename the PR name to be more relevant to the change.

**Comment by anshulahuja98** [comment]
Also @yanggangtony the CI is failing, pl check

**Comment by yanggangtony** [comment]
wait.

**Comment by yanggangtony** [comment]
@anshulahuja98 
Bump the go version to 1.21 , how to trigger the ci runs?
Is that just you can?

**Comment by anshulahuja98** [comment]
Ran it.

**Review by ywk253100 — APPROVED** [review]

**Comment by mykolaichuk** [comment]
Hi @anshulahuja98 

You've mentioned that MSI support was in place previously. Is it there now? Is there a usage documentation for this?

Thanks in advance!

**Comment by anshulahuja98** [comment]
It is there now in the repo.

For end users to consume MSI - I would recommend using Workload Identity.

There is no public docs for using MSI without workload identity in AKS. I can point you further but would still recommend using WorkloadIdentity.

**Comment by mykolaichuk** [comment]
Could you be so kind as to give me snippets or a short guide for MSI without workload identity, please?

I have two AAD enabled clusters in different subscriptions and struggle with workload identity setup.

**Comment by anshulahuja98** [comment]
Basically by virtue of being mounted on the nodepool, the IMDS endpoint of the VM will return the auth for the MSI client ID.

**Comment by mykolaichuk** [comment]
@anshulahuja98 thank you so much! It worked! I had some issues with a storage account, but I was able to deal with it on my own!

**Comment by anshulahuja98** [comment]
Glad I could help you out :)

**Pull request merged**
