### PR TITLE
add support for incremental snapshots of Azure disks

### LINKED ISSUE #25: support incremental snapshots of Azure disks
https://azure.microsoft.com/ru-ru/blog/introducing-cost-effective-increment-snapshots-of-azure-managed-disks-in-preview/

### PR DESCRIPTION
**Pull request by stephanwehr**
Closes #25 

Passed the following test cases:

Test: Omit parameter "incremental"
Result: Full snapshot taken

Test: Set parameter "incremental" to "true"
Result: Incremental snapshot taken

Test: Set parameter "incremental" to "test value"
Result: Backup fails partially, no snapshot taken, error message in log

### CODE REVIEW

**Comment by stephanwehr** [comment]
signed off the commit

**Comment by ashish-amarnath** [comment]
@stephanwehr Thank you for your PR.
Can you please confirm if you've been able to run this PR through any tests and tell us what those tests were? 
I am trying to think how this should be tested apart from having no regressions in behavior.

**Comment by ashish-amarnath** [comment]
closing and reopening to re-trigger DCO

**Comment by ashish-amarnath** [comment]
That didn't seem to work.
Can you please follow the instructions from https://github.com/vmware-tanzu/velero-plugin-for-microsoft-azure/pull/52/checks?check_run_id=770044678 to sign your commits again? It may have something to do with a missing new-line before the `Signed-off:...`

**Comment by stephanwehr** [comment]
Completed DCO

The tests mentioned in the 1st comment were done manually against an AKS cluster.
@Juhibhadviya19 Could you please confirm the behavior of the 3 test cases?

To get the error message of the 3rd test case run:
`velero backup logs <name-of-the-failed-backup`
Make sure no snapshot is taken in Azure if the backup fails.

**Comment by Juhibhadviya19** [comment]
@stephanwehr  All the 3 test cases behaved as mentioned by you

**Comment by nrb** [comment]
@stephanwehr and @Juhibhadviya19 thanks for the testing!

When restoring from an incremental snapshot, is there any difference in usage, or does Azure do the association under the covers?

**Comment by ashish-amarnath** [comment]
There is no difference in the usage. The Azure sdk takes care of this for us. From Velero's perspective, it is the usual `velero restore ` command. One scenario I forgot to verify is:
1. Create a backup with incremental snapshot enabled.
2. Restore from that backup with incremental snapshotting disabled.

Is this a scenario that you were able to verify @Juhibhadviya19 ?

**Comment by ashish-amarnath** [comment]
I think something is not right. Give me a few min to figure out what's going on.

**Comment by ashish-amarnath** [comment]
@nrb this is ready for merge, unless you have other questions or comments

**Comment by nrb** [comment]
Thanks for testing that all @ashish-amarnath!

**Comment by Sathishkunisai** [comment]
tentative time for releasing fix for Incremental backup for AKS PVC, Please.

**Comment by ashish-amarnath** [comment]
@Sathishkunisai We should have a release with this change end of august, at the same time as Velero 1.5.
However, you can start using this feature using the [velero/velero-plugin-for-microsoft-azure:main](https://hub.docker.com/layers/velero/velero-plugin-for-microsoft-azure/main/images/sha256-307046a746fc68d244f019067d903d4a5ff10b7c5c53f8dc0282558ffe8c7888?context=repo) image for the plugin.

**Pull request merged**
