### PR TITLE
change `install` to `add`

### PR DESCRIPTION
**Pull request by fluffyf-x**
velero version
```
Client:
	Version: v1.6.0
	Git commit: -
Server:
	Version: v1.6.0
```
attempt to install plugin: 
``` 
velero plugin install velero/velero-plugin-for-microsoft-azure:v1.2.0
Work with plugins

Usage:
  velero plugin [command]

Available Commands:
  add         Add a plugin
  get         Get information for all plugins on the velero server
  remove      Remove a plugin
```

### CODE REVIEW

**Comment by fluffyf-x** [comment]
Hey, install wasn't a recogized option under the plugin? Could you please look this over?
Thank you for your hard work!

**Review by zubron — CHANGES_REQUESTED** [review]
Good spot, thanks for catching this! Please sign off your commit using the instructions [here](https://github.com/vmware-tanzu/velero-plugin-for-microsoft-azure/pull/95/checks?check_run_id=2412893081) and then we can merge this. Thanks!

**Comment by jenting** [comment]
> Good spot, thanks for catching this! Please sign off your commit using the instructions [here](https://github.com/vmware-tanzu/velero-plugin-for-microsoft-azure/pull/95/checks?check_run_id=2412893081) and then we can merge this. Thanks!

@fluffyf-x ping.

**Comment by jenting** [comment]
#104 fix the issue, close this PR.

**Pull request closed without merging**
