### PR TITLE
Bump version of Azure Compute SDK to support Prem SSD V2

### PR DESCRIPTION
**Pull request by wyattfry**

### CODE REVIEW

**Comment by ywk253100** [comment]
@wyattfry Please check the CI failure

**Comment by wyattfry** [comment]
> @wyattfry Please check the CI failure

Yeah, it's because go.mod and go.sum weren't updated, but when I update them, all those other changes are automatically made that you asked not to include, so I'm not sure what to do.

**Review by ywk253100 — APPROVED** [review]

**Comment by ywk253100** [comment]
@wyattfry Could you resolve the conflict of the PR?

**Comment by ywk253100** [comment]
Submit another [PR](https://github.com/vmware-tanzu/velero-plugin-for-microsoft-azure/pull/215) to resolve the conflict, closing this one

**Pull request closed without merging**
