### PR TITLE
Refine the minimum permissions needed by Velero in README

### PR DESCRIPTION
**Pull request by ywk253100**
Refine the minimum permissions needed by Velero in README

Signed-off-by: Wenkai Yin(尹文开) <yinw@vmware.com>

### CODE REVIEW

**Comment by ywk253100** [comment]
Fixes https://github.com/vmware-tanzu/velero/issues/3154

**Review by a-mccarthy — DISMISSED** [review]
@ywk253100 I think these changes look great! I am not familiar with Azure permissions, so i'd also recommend getting a second review from another maintainer/community member to have a second pair of eyes on the tech pieces of this PR. 

I'm approving the changes, but have one question/suggestion. Is the information in the removed Storage account, snapshot and disk management sections still valid? I like the way the required permissions are listed out with bullet points. I think it makes the information very clear to read and scan for. If it's still correct, i'd suggest keep it in the doc right before the improved section on how to create roles and assign these permissions that you added. 

You have included the information within the new content you added, so it's maybe not necessary, but it might be more clear to have it both ways for users. If it's no longer valid, then obviously it should be removed.

**Comment by ywk253100** [comment]
> @ywk253100 I think these changes look great! I am not familiar with Azure permissions, so i'd also recommend getting a second review from another maintainer/community member to have a second pair of eyes on the tech pieces of this PR.
> 
> I'm approving the changes, but have one question/suggestion. Is the information in the removed Storage account, snapshot and disk management sections still valid? I like the way the required permissions are listed out with bullet points. I think it makes the information very clear to read and scan for. If it's still correct, i'd suggest keep it in the doc right before the improved section on how to create roles and assign these permissions that you added.
> 
> You have included the information within the new content you added, so it's maybe not necessary, but it might be more clear to have it both ways for users. If it's no longer valid, then obviously it should be removed.

It is still valid, I will take it back as you suggested, thanks.

**Review by blackpiglet — APPROVED** [review]

**Review by a-mccarthy — APPROVED** [review]
lgtm!

**Pull request merged**
