### PR TITLE
[old] Bump version of Azure Compute SDK to support Prem SSD V2

### PR DESCRIPTION
**Pull request by wyattfry**
Linked to this issue: https://github.com/vmware-tanzu/velero/issues/6650

### CODE REVIEW

**Comment by ywk253100** [comment]
@wyattfry Could you change the PR to only contain the package bumping up related code?

**Comment by wyattfry** [comment]
> @wyattfry Could you change the PR to only contain the package bumping up related code?

I'm not sure how those other changes got in there. Regardless, pushing new commits with the version change isolated

**Comment by wyattfry** [comment]
> > @wyattfry Could you change the PR to only contain the package bumping up related code?
> 
> I'm not sure how those other changes got in there. Regardless, pushing new commits with the version change isolated

Looks like they got put back in, i have no idea how / why but I'm not doing it.

**Comment by wyattfry** [comment]
i tried changing the base branch to 1.8 but didn't seem to help

**Comment by wyattfry** [comment]
@ywk253100 do you understand where those other changes are coming from?

**Comment by ywk253100** [comment]
@wyattfry Try to rebase to the main branch HEAD of the upstream or create a new PR with the necessary changes.

**Comment by wyattfry** [comment]
I opted for new PR: https://github.com/vmware-tanzu/velero-plugin-for-microsoft-azure/pull/207

**Pull request closed without merging**
