### PR TITLE
support aad-pod-identity auth

### LINKED ISSUE #11: Azure Service Principal authentication using certificates
The Velero documentation authenticates against azure using Service Principal and a client secret.

However, you can also authenticate using a certificate. We're in quite a strict environment and have no secrets. 

This is a feature request to add the ability to authenticate using a certificate also.

Relevent code: https://github.com/heptio/velero/blob/0fd7872ef48ce617e561e6e45f8ccb0f11637f58/pkg/cloudprovider/azure/common.go#L57

Azure autorest/adal method to use certificates: https://github.com/Azure/go-autorest/blob/master/autorest/adal/token.go#L535

Related to this issue: https://github.com/heptio/velero/issues/379
Longer term it's probably best to move to using https://github.com/Azure/aad-pod-identity

- Cloud provider: Azure

### LINKED ISSUE #12: Azure: support getting credentials using aad-pod-identity
Using aad-pod-identity, in combination with azure identities, it is possible for the cloud provider to get credentials without having to pass them in as environmental variables. Instead, the azure api uses the metadata service to query its current identity (provided by aad-pod-identity) and returns the required client for access.

This is very much like how kiam works.

Can we update the Azure cloud provider to provide this authentication method? Has anyone got this to work already with a work around (e.g. having an external pod get credentials and inject them into the velero pod)?

This has already been discussed here (#379) but was closed. This is also related to vmware-tanzu/velero-plugin-for-microsoft-azure#11.

### PR DESCRIPTION
**Pull request by skriss**
Signed-off-by: Steve Kriss <krisss@vmware.com>

updates/replaces #29 

closes #11 
closes #12

### CODE REVIEW

**Comment by skriss** [comment]
cross-posting from the original PR:

@ezYakaEagle442 if you have bandwidth to test, I pushed two images: steveheptio/velero:aad-pod-identity and steveheptio/velero-plugin-for-microsoft-azure:aad-pod-identity. The former is only needed if you're using the restic integration. I did a quick test with them and it seems to be working properly, but I'd love to get more eyes and I still need to regression-test with SP auth.

I used a similar setup process to your script, but I used the following role assignment (based on our existing docs for SP auth):
--role "Contributor" --scopes /subscriptions/$AZURE_SUBSCRIPTION_ID

And then I manually added the aadpodidbinding label to the Velero pods (via the deployment & daemonset's pod template spec)

**Comment by skriss** [comment]
OK, I've successfully tested both `aad-pod-identity` auth and service principal auth using this code (including full backup and restore). This is now ready for review.

@ezYakaEagle442 I'm still very interested in having you test this as well.

**Comment by ezYakaEagle442** [comment]
@skriss hi, I was off a few days, I have a couple of priorities to manage first but I would be happy to help, I will do my best to test it asap, I will let you know my results

**Comment by skriss** [comment]
@carlisia @nrb PTAL (related to already-merged https://github.com/vmware-tanzu/velero/pull/2602)

**Pull request merged**
