### PR TITLE
Update the documents for the release 1.3.0

### PR DESCRIPTION
**Pull request by ywk253100**
Signed-off-by: Wenkai Yin(尹文开) <yinw@vmware.com>

### CODE REVIEW

**Review by jenting — COMMENTED** [review]
I think it should be merged after v1.3.0 is released.
I'll review it again once v1.3.0 is released.

**Comment by ywk253100** [comment]
@jenting Thank you for the quick response.
We want to make a RC tag and do some testing based on the RC builds of velero and the plugin. If everything goes well, we will make the GA release from the same commit of the RC directly
So please take a look at this PR

**Comment by jenting** [comment]
Okay, but I'd prefer separate 2 PRs, one is for RC build and the other one is for updating the README.

**Comment by ywk253100** [comment]
@jenting We just want to make sure all releases follow the same process, the documents are ready for RC release of main velero, so here same to the plugins :slightly_smiling_face:

**Comment by jenting** [comment]
Fine. I just want to make sure the user won't use the wrong version/tag when reading the README of this plugin during the RC testng.
NVM, I'll approve it.

**Review by jenting — APPROVED** [review]

**Comment by reasonerjt** [comment]
Thanks @jenting

**Review by reasonerjt — APPROVED** [review]

**Pull request merged**
